networks:
  spark-network:
    driver: bridge
  zookeeper_zookeeper-network:
    external: true

services:
  spark-master:
    image: ${SPARK_IMAGE}
    container_name: spark-master
    hostname: spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT_NUMBER: 7077
      SPARK_LOG_LEVEL: ${SPARK_LOG_LEVEL}
      SPARK_DAEMON_JAVA_OPTS: >-
        -Dspark.deploy.recoveryMode=zookeeper
        -Dspark.deploy.zookeeper.url=${SPARK_ZOOKEEPER_URL}
        -Dspark.deploy.zookeeper.dir=${SPARK_ZOOKEEPER_DIR}
        -Dspark.deploy.zookeeper.connectionTimeout=10000
        -Dspark.deploy.zookeeper.sessionTimeout=10000
        -Dspark.deploy.zookeeper.retryCount=3
        -Dspark.deploy.zookeeper.retryInterval=1000
        -Dspark.deploy.zookeeper.retryMax=10
    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_MASTER_WEB_PORT}:8080"
    volumes:
      - ./data/spark-master:${SPARK_WORK_DIR}
      - ./logs/spark-master:${SPARK_LOG_DIR}
    networks:
      - spark-network
      - zookeeper_zookeeper-network
    restart: unless-stopped
    mem_limit: ${SPARK_MEM_LIMIT}
    cpus: ${SPARK_CPU_LIMIT}

  spark-worker-1:
    image: ${SPARK_IMAGE}
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_LOG_LEVEL: ${SPARK_LOG_LEVEL}
    ports:
      - "${SPARK_WORKER_WEB_PORT1}:8081"
    volumes:
      - ./data/spark-worker-1:${SPARK_WORK_DIR}
      - ./logs/spark-worker-1:${SPARK_LOG_DIR}
    networks:
      - spark-network
      - zookeeper_zookeeper-network
    restart: unless-stopped
    mem_limit: ${SPARK_MEM_LIMIT}
    cpus: ${SPARK_CPU_LIMIT}
    depends_on:
      - spark-master

  spark-worker-2:
    image: ${SPARK_IMAGE}
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_LOG_LEVEL: ${SPARK_LOG_LEVEL}
    ports:
      - "${SPARK_WORKER_WEB_PORT2}:8081"
    volumes:
      - ./data/spark-worker-2:${SPARK_WORK_DIR}
      - ./logs/spark-worker-2:${SPARK_LOG_DIR}
    networks:
      - spark-network
      - zookeeper_zookeeper-network
    restart: unless-stopped
    mem_limit: ${SPARK_MEM_LIMIT}
    cpus: ${SPARK_CPU_LIMIT}
    depends_on:
      - spark-master
