services:
  zookeeper1:
    image: imdhruv99/zookeeper:1.0.0
    container_name: zookeeper1
    hostname: zookeeper1
    environment:
      ZOOKEEPER_MYID: 1
      ZOOKEEPER_SERVERS: |
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 9999:9999
    volumes:
      - zookeeper1-data:/var/lib/zookeeper/data
      - zookeeper1-logs:/var/lib/zookeeper/logs
    networks:
      - zookeeper_net

  zookeeper2:
    image: imdhruv99/zookeeper:1.0.0
    container_name: zookeeper2
    hostname: zookeeper2
    environment:
      ZOOKEEPER_MYID: 2
      ZOOKEEPER_SERVERS: |
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    entrypoint: [ "sh", "-c", "sleep 5 && exec /usr/local/bin/docker-entrypoint.sh" ]
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888
      - 9992:9999
    volumes:
      - zookeeper2-data:/var/lib/zookeeper/data
      - zookeeper2-logs:/var/lib/zookeeper/logs
    networks:
      - zookeeper_net

  zookeeper3:
    image: imdhruv99/zookeeper:1.0.0
    container_name: zookeeper3
    hostname: zookeeper3
    environment:
      ZOOKEEPER_MYID: 3
      ZOOKEEPER_SERVERS: |
        server.1=zookeeper1:2888:3888;2181
        server.2=zookeeper2:2888:3888;2181
        server.3=zookeeper3:2888:3888;2181
    entrypoint: [ "sh", "-c", "sleep 10 && exec /usr/local/bin/docker-entrypoint.sh" ]
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888
      - 9993:9999
    volumes:
      - zookeeper3-data:/var/lib/zookeeper/data
      - zookeeper3-logs:/var/lib/zookeeper/logs
    networks:
      - zookeeper_net

volumes:
  zookeeper1-data:
  zookeeper1-logs:
  zookeeper2-data:
  zookeeper2-logs:
  zookeeper3-data:
  zookeeper3-logs:

networks:
  zookeeper_net:
    driver: bridge
