networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_SHARED_PRELOAD_LIBRARIES: ${POSTGRES_SHARED_PRELOAD_LIBRARIES}
      POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS}
      POSTGRES_EFFECTIVE_CACHE_SIZE: ${POSTGRES_EFFECTIVE_CACHE_SIZE}
      POSTGRES_WORK_MEM: ${POSTGRES_WORK_MEM}
      POSTGRES_MAINTENANCE_WORK_MEM: ${POSTGRES_MAINTENANCE_WORK_MEM}
      POSTGRES_CHECKPOINT_SEGMENTS: ${POSTGRES_CHECKPOINT_SEGMENTS}
      POSTGRES_WAL_BUFFERS: ${POSTGRES_WAL_BUFFERS}
      POSTGRES_DEFAULT_STATISTICS_TARGET: ${POSTGRES_DEFAULT_STATISTICS_TARGET}
      POSTGRES_RANDOM_PAGE_COST: ${POSTGRES_RANDOM_PAGE_COST}
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: ${POSTGRES_EFFECTIVE_IO_CONCURRENCY}
      POSTGRES_MIN_WAL_SIZE: ${POSTGRES_MIN_WAL_SIZE}
      POSTGRES_MAX_WAL_SIZE: ${POSTGRES_MAX_WAL_SIZE}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    networks:
      - postgres-network
    mem_limit: ${POSTGRES_MEM_LIMIT}
    cpus: ${POSTGRES_CPU_LIMIT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: pgadmin
    hostname: pgadmin
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres-network
    depends_on:
      - postgres
    restart: unless-stopped
