networks:
  kafka-network:
    driver: bridge

services:
  kafka-broker-1:
    image: ${KAFKA_IMAGE}
    container_name: kafka-broker-1
    hostname: kafka-broker-1
    networks:
      - kafka-network
    ports:
      - "19091:9091"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:9092,EXTERNAL://localhost:19091
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LOG_DIRS: ${KAFKA_CFG_LOG_DIRS}
      KAFKA_CFG_LOG_RETENTION_HOURS: ${KAFKA_CFG_LOG_RETENTION_HOURS}
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_CFG_NUM_PARTITIONS: ${KAFKA_CFG_NUM_PARTITIONS}
      KAFKA_CFG_LOG_SEGMENT_BYTES: ${KAFKA_CFG_LOG_SEGMENT_BYTES}
      KAFKA_CFG_LOG_CLEANER_ENABLE: ${KAFKA_CFG_LOG_CLEANER_ENABLE}
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: ${KAFKA_CFG_DEFAULT_REPLICATION_FACTOR}
      KAFKA_CFG_MIN_INSYNC_REPLICAS: ${KAFKA_CFG_MIN_INSYNC_REPLICAS}
      KAFKA_CFG_MESSAGE_MAX_BYTES: ${KAFKA_CFG_MESSAGE_MAX_BYTES}
    volumes:
      - ./data/kafka1:/bitnami/kafka/data
    mem_limit: ${KAFKA_MEM_LIMIT}
    cpus: ${KAFKA_CPU_LIMIT}

  kafka-broker-2:
    image: ${KAFKA_IMAGE}
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    networks:
      - kafka-network
    ports:
      - "19092:9091"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:9092,EXTERNAL://localhost:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LOG_DIRS: ${KAFKA_CFG_LOG_DIRS}
      KAFKA_CFG_LOG_RETENTION_HOURS: ${KAFKA_CFG_LOG_RETENTION_HOURS}
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_CFG_NUM_PARTITIONS: ${KAFKA_CFG_NUM_PARTITIONS}
      KAFKA_CFG_LOG_SEGMENT_BYTES: ${KAFKA_CFG_LOG_SEGMENT_BYTES}
      KAFKA_CFG_LOG_CLEANER_ENABLE: ${KAFKA_CFG_LOG_CLEANER_ENABLE}
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: ${KAFKA_CFG_DEFAULT_REPLICATION_FACTOR}
      KAFKA_CFG_MIN_INSYNC_REPLICAS: ${KAFKA_CFG_MIN_INSYNC_REPLICAS}
      KAFKA_CFG_MESSAGE_MAX_BYTES: ${KAFKA_CFG_MESSAGE_MAX_BYTES}
    volumes:
      - ./data/kafka2:/bitnami/kafka/data
    mem_limit: ${KAFKA_MEM_LIMIT}
    cpus: ${KAFKA_CPU_LIMIT}

  kafka-broker-3:
    image: ${KAFKA_IMAGE}
    container_name: kafka-broker-3
    hostname: kafka-broker-3
    networks:
      - kafka-network
    ports:
      - "19093:9091"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-3:9092,EXTERNAL://localhost:19093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LOG_DIRS: ${KAFKA_CFG_LOG_DIRS}
      KAFKA_CFG_LOG_RETENTION_HOURS: ${KAFKA_CFG_LOG_RETENTION_HOURS}
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_CFG_NUM_PARTITIONS: ${KAFKA_CFG_NUM_PARTITIONS}
      KAFKA_CFG_LOG_SEGMENT_BYTES: ${KAFKA_CFG_LOG_SEGMENT_BYTES}
      KAFKA_CFG_LOG_CLEANER_ENABLE: ${KAFKA_CFG_LOG_CLEANER_ENABLE}
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: ${KAFKA_CFG_DEFAULT_REPLICATION_FACTOR}
      KAFKA_CFG_MIN_INSYNC_REPLICAS: ${KAFKA_CFG_MIN_INSYNC_REPLICAS}
      KAFKA_CFG_MESSAGE_MAX_BYTES: ${KAFKA_CFG_MESSAGE_MAX_BYTES}
    volumes:
      - ./data/kafka3:/bitnami/kafka/data
    mem_limit: ${KAFKA_MEM_LIMIT}
    cpus: ${KAFKA_CPU_LIMIT}

  kafka-ui:
    image: ${KAFKA_UI_IMAGE}
    container_name: kafka-ui
    networks:
      - kafka-network
    ports:
      - "18080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_ID}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_ENABLED: "false"
